### ISSUE TITLE
Error: No Instance(s) Available.

### ISSUE THREAD

**Issue by soulmonk** [tomas/network#1]
Hi, can you help me, with this issue: on windows i found that when any method try found any info (like  os_functions.netmask_for etc.) by "nic_name" it throws "Error: No Instance(s) Available."
I found this bug because of my system encoding is not 'utf8' and recive information in wrong encoding.

Is there any simple decision?

**Comment by tomas** [comment]
If anyone's still interested, I merged @Komanaki's fix onto wmic and pushed a new version of that module to npm. So you can now try doing a `npm install wmic@0.1.0` and see if it works.

@tonila, @soulmonk ?

**Comment by tonila** [comment]
I don't have Windows 7 anymore and Windows 10 has named network interface as "Ethernet" regardless of the finnish localization. 

But I tested by adding "ä" to the network interface name and now it seems to work as expected.

**Comment by tomas** [comment]
Ok, thanks to @tonila's feedback I'm (finally) closing this issue. 

Just pushed network v0.2.0 to npm, by the way, which uses the updated `wmic` package.

Thanks everyone for the help and patience. ;)
