### ISSUE TITLE
Mask bug

### ISSUE THREAD

**Issue by winox** [tomas/network#14]
Hi!
code:
> var network = require('network');
> network.get_active_interface(function(err, obj) {
>     console.log(obj);
> });

result is:
> root@raspbx:~/siren# node test
> { name: 'eth0',
>   ip_address: '192.168.88.174',
>   mac_address: 'b8:27:eb:a8:b4:7a',
>   gateway_ip: '192.168.88.1',
>   netmask: 'Mask:255.255.255.0' } //WTF?? netmask: 'Mask ?

os Raspbian 8.0
nodejs v7.1.0
Thanks!

**Comment by tomas** [comment]
Look like a parser error. Let me take a look at it.

**Comment by tomas** [comment]
Fixed! New version pushed to the npm registry.
