### ISSUE TITLE
Calling get_interfaces_list on Windows does not return the gateway address

### ISSUE THREAD

**Issue by kevinhikaruevans** [tomas/network#2]
The examples show the array containing objects with the gateway addresses, but it does not return it on Windows. It does have the IP/Mac/Name/Model/Vendor/Type though.

**Comment by jeniaSakirko** [comment]
I have the same problem

**Comment by tomas** [comment]
It looks like that Windows [does not provide](https://github.com/tomas/network/blob/master/lib/win32.js#L61-L69) an interface's gateway IP through the wmic utility, which is what this module uses to get the information. It can only show the active gateway IP.

I guess I'll need to update the readme... sorry. 

If you do find a way to get this information I'll be happy to update the code.

**Comment by jeniaSakirko** [comment]
Hey you can try:
wmic.get_values('nicconfig', 'DefaultIPGateway, DHCPServer', `MACAddress = '${mac_address}'`, function(err, res) {
})
