### ISSUE TITLE
get_active_interface doesn't work on Mac OS Catalina 10.15.2

### ISSUE THREAD

**Issue by Talb2005** [tomas/network#38]
Throws error 

> No active interfaces detected.

I've tracked the issue down to the function 'get_active_network_interface_name'.
`var cmd = "netstat -rn | grep UG | awk '{print $6}'";`
running this command on my Mac returns an empty string.

I noticed that in linux.js the command is `var cmd = "netstat -rn | grep UG | awk '{print $NF}'";` 
Perhaps it should be the same for darwin.js?

**Comment by RicardoMiguel** [comment]
+1

**Comment by tomas** [comment]
I think #39 should fix this.

**Comment by Talb2005** [comment]
@tomas any chance #39 would be merged in the next few days?

**Comment by tomas** [comment]
Just published 0.5.0
