### ISSUE TITLE
Calling get_interfaces_list on Windows 7 does not return the ip address

### ISSUE THREAD

**Issue by aaleks** [tomas/network#5]
The examples show the array containing objects with the ip addresses, but it does not return it on Windows for a wireless interface (Intel Centurion Advanced-N 6230. It does have the Mac/Name/Model/Vendor/Type. 

Moreover the active interface for the wireless interface doesn't return anything from network.get_active_interface. 

Doing ipconfig show me that the interface as an IP address.

**Comment by tomas** [comment]
Is Windows set up in english or another language?

**Comment by aaleks** [comment]
Windows is set up in French.

**Comment by tomas** [comment]
Can you try using the latest version and see if the problem is still present?

**Comment by aaleks** [comment]
I will give a try and come back to tell if it's working :)

**Comment by tomas** [comment]
Great, thanks.

**Comment by aaleks** [comment]
On my macbook pro retina it is not working anymore when going to 0.2.0 from 0.1.3. 

The two methods are always returning undefined now with 0.2.0
network.get_active_interface(function (err, obj){})
network.get_interfaces_list(function (err, list){})

Going back to 0.1.3 is working well again. Didn't try on Windows for the moment

**Comment by tomas** [comment]
Shoot, I'll take a look a this in a minute.

**Comment by tomas** [comment]
Fixed and published 0.2.1! My bad, sorry.

**Comment by aaleks** [comment]
Work again thanks! Will try it on windows and keep you up to date!

**Comment by aaleks** [comment]
It also work on Windows 7 in french now 👍 Thanks
